### ISSUE TITLE
No total value amount given when selecting fiats other than USD.

### ISSUE THREAD

**Issue by anaelleltd** [James-Sangalli/dot-staking-income-web#7]
I submitted my KSM address and the spreadsheet came out fine with USD.
However, when I changed the fiat currency (to EURO or AUD), the spreadsheet came with the table header "total_value_usd" and a blank cell. 

What to do? -_-

![SI_error](https://user-images.githubusercontent.com/44770354/130013041-21221fb2-f603-49da-ae81-65b276fc3f56.JPG)

**Comment by JamesANZ** [comment]
Hi @anaelleltd thanks for reporting this issue.

I am currently not able to reproduce this with my KSM address as I get the AUD value; however this was an issue a while ago before I fixed it here: https://github.com/James-Sangalli/dot-staking-income/commit/ebb33edb5b92e9e13c08f293eb0836f4e3624644

To ensure this is not a caching error, could you please either clear the cache, try it in another browser or try it in incognito mode and let me know if it does the same thing again

**Comment by anaelleltd** [comment]
Fab! Working on a different browser now.
Cheers! 👍
